/**
 * Job Scraper Service
 * Fetches jobs from JSearch (RapidAPI), maps them to our DB schema,
 * stores them with embeddings generated by the ML service.
 */

import { db } from "../db";
import * as schema from "../db/schema";
import { eq, sql } from "drizzle-orm";
import { ML_API_URL } from "../config";

const RAPIDAPI_KEY = process.env.RAPIDAPI_KEY || "";
const JSEARCH_HOST = "jsearch.p.rapidapi.com";
const SYSTEM_RECRUITER_ID = process.env.SYSTEM_RECRUITER_ID || "";

// ── Type maps ──────────────────────────────────────────────────────

const JOB_TYPE_MAP: Record<string, string> = {
  FULLTIME: "full_time",
  PARTTIME: "part_time",
  CONTRACTOR: "contract",
  CONTRACT: "contract",
  INTERN: "internship",
};

function mapJobType(raw?: string | null): "full_time" | "part_time" | "contract" | "internship" | null {
  if (!raw) return null;
  return (JOB_TYPE_MAP[raw.toUpperCase()] as any) || "full_time";
}

function mapWorkType(isRemote?: boolean | null): "remote" | "hybrid" | "onsite" | null {
  if (isRemote == null) return null;
  return isRemote ? "remote" : "onsite";
}

// ── Experience parsing ─────────────────────────────────────────────

function parseExperience(text: string): { min: number | null; max: number | null } {
  if (!text) return { min: null, max: null };

  const rangeMatch = text.match(/(\d+)\s*[-–to]+\s*(\d+)\s*(?:years?|yrs?)/i);
  if (rangeMatch) return { min: +rangeMatch[1], max: +rangeMatch[2] };

  const singleMatch = text.match(/(\d+)\+?\s*(?:years?|yrs?)/i);
  if (singleMatch) return { min: +singleMatch[1], max: null };

  return { min: null, max: null };
}

// ── Skill extraction ───────────────────────────────────────────────

const COMMON_SKILLS = new Set([
  "python", "java", "javascript", "typescript", "c++", "c#", "go", "rust",
  "ruby", "php", "swift", "kotlin", "scala", "sql",
  "react", "angular", "vue", "next.js", "node.js", "express", "django",
  "flask", "fastapi", "spring", "rails", "laravel",
  "aws", "azure", "gcp", "docker", "kubernetes", "terraform", "jenkins",
  "git", "linux", "nginx", "redis", "kafka",
  "postgresql", "mysql", "mongodb", "dynamodb", "elasticsearch",
  "graphql", "rest", "grpc", "websocket",
  "machine learning", "deep learning", "nlp", "computer vision",
  "tensorflow", "pytorch", "scikit-learn", "pandas", "numpy",
  "html", "css", "tailwind", "sass", "figma",
  "data engineering", "data science", "data analysis",
  "spark", "hadoop", "airflow",
  "microservices", "system design", "api design",
  "ci/cd", "agile", "scrum",
]);

function extractSkills(text: string): string[] {
  const lower = text.toLowerCase();
  const found: string[] = [];
  for (const skill of COMMON_SKILLS) {
    if (skill.length <= 2) {
      if (new RegExp(`\\b${skill.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`).test(lower)) {
        found.push(skill);
      }
    } else if (lower.includes(skill)) {
      found.push(skill);
    }
  }
  return found;
}

// ── Company upsert ─────────────────────────────────────────────────

async function upsertCompany(
  name: string,
  logoUrl?: string | null,
  website?: string | null,
): Promise<string | null> {
  if (!name) return null;

  const [existing] = await db
    .select({ id: schema.companies.id })
    .from(schema.companies)
    .where(sql`LOWER(${schema.companies.name}) = LOWER(${name})`)
    .limit(1);

  if (existing) return existing.id;

  const [created] = await db
    .insert(schema.companies)
    .values({
      name,
      logoUrl: logoUrl || null,
      website: website || null,
    })
    .returning({ id: schema.companies.id });

  return created.id;
}

// ── Job embedding via ML service ───────────────────────────────────

async function generateJobEmbedding(
  title: string,
  description: string,
  requirements: string,
): Promise<number[] | null> {
  try {
    const resp = await fetch(`${ML_API_URL}/api/v1/job/embedding`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title, description, requirements }),
    });

    if (!resp.ok) {
      console.error("ML embedding failed:", resp.status);
      return null;
    }

    const data = await resp.json();
    return data.embedding || null;
  } catch (err) {
    console.error("ML embedding error:", err);
    return null;
  }
}

// ── Link skills to job ─────────────────────────────────────────────

async function linkJobSkills(jobId: string, skills: string[]) {
  for (const skillName of skills) {
    let [existing] = await db
      .select({ id: schema.skillsMaster.id })
      .from(schema.skillsMaster)
      .where(sql`LOWER(${schema.skillsMaster.name}) = LOWER(${skillName})`)
      .limit(1);

    if (!existing) {
      [existing] = await db
        .insert(schema.skillsMaster)
        .values({ name: skillName })
        .returning({ id: schema.skillsMaster.id });
    }

    await db
      .insert(schema.jobSkills)
      .values({ jobId, skillId: existing.id })
      .onConflictDoNothing();
  }
}

// ── Fetch from JSearch API ─────────────────────────────────────────

interface JSearchJob {
  job_title?: string;
  job_description?: string;
  employer_name?: string;
  employer_logo?: string;
  employer_website?: string;
  job_employment_type?: string;
  job_is_remote?: boolean;
  job_city?: string;
  job_state?: string;
  job_country?: string;
  job_min_salary?: number | null;
  job_max_salary?: number | null;
  job_offer_expiration_datetime_utc?: string;
  job_apply_link?: string;
  job_highlights?: {
    Qualifications?: string[];
    Responsibilities?: string[];
  };
}

async function fetchFromJSearch(
  query: string,
  location: string = "India",
  page: number = 1,
  numPages: number = 1,
  datePosted: string = "week",
): Promise<JSearchJob[]> {
  if (!RAPIDAPI_KEY) throw new Error("RAPIDAPI_KEY not set");

  const params = new URLSearchParams({
    query: `${query} in ${location}`,
    page: String(page),
    num_pages: String(numPages),
    date_posted: datePosted,
    country: "in",
  });

  const resp = await fetch(`https://${JSEARCH_HOST}/search?${params}`, {
    headers: {
      "X-RapidAPI-Key": RAPIDAPI_KEY,
      "X-RapidAPI-Host": JSEARCH_HOST,
    },
  });

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`JSearch API error ${resp.status}: ${text}`);
  }

  const data = await resp.json();
  return data.data || [];
}

// ── Store single job ───────────────────────────────────────────────

async function storeJob(jobData: JSearchJob): Promise<string | null> {
  const title = (jobData.job_title || "").slice(0, 200);
  const employer = jobData.employer_name || "";
  const description = jobData.job_description || "";

  if (!title || !description) return null;

  // Check duplicate
  const [dup] = await db
    .select({ id: schema.jobs.id })
    .from(schema.jobs)
    .innerJoin(schema.companies, eq(schema.jobs.companyId, schema.companies.id))
    .where(
      sql`LOWER(${schema.jobs.jobTitle}) = LOWER(${title})
          AND LOWER(${schema.companies.name}) = LOWER(${employer})`,
    )
    .limit(1);

  if (dup) return null; // duplicate

  // Build requirements text
  const highlights = jobData.job_highlights || {};
  const quals = highlights.Qualifications || [];
  const resps = highlights.Responsibilities || [];
  let requirementsText = "";
  if (quals.length) requirementsText += "Qualifications:\n" + quals.map((q) => `• ${q}`).join("\n");
  if (resps.length) {
    if (requirementsText) requirementsText += "\n\n";
    requirementsText += "Responsibilities:\n" + resps.map((r) => `• ${r}`).join("\n");
  }

  // Parse fields
  const exp = parseExperience(description + " " + requirementsText);
  const locationParts = [jobData.job_city, jobData.job_state, jobData.job_country].filter(Boolean);
  const jobLocation = locationParts.length ? locationParts.join(", ").slice(0, 200) : null;

  let expiresAt: Date | null = null;
  if (jobData.job_offer_expiration_datetime_utc) {
    try {
      expiresAt = new Date(jobData.job_offer_expiration_datetime_utc);
    } catch {
      // ignore
    }
  }

  // Upsert company
  const companyId = await upsertCompany(
    employer,
    jobData.employer_logo,
    jobData.employer_website,
  );

  // Generate embedding via ML service
  const embedding = await generateJobEmbedding(title, description, requirementsText);
  const embeddingStr = embedding ? `[${embedding.join(",")}]` : null;

  // Insert job
  const [job] = await db
    .insert(schema.jobs)
    .values({
      recruiterId: SYSTEM_RECRUITER_ID,
      companyId,
      jobTitle: title,
      jobDescription: description,
      jobRequirement: requirementsText || null,
      minExperience: exp.min ?? 0,
      maxExperience: exp.max,
      minSalary: jobData.job_min_salary?.toString() || null,
      maxSalary: jobData.job_max_salary?.toString() || null,
      jobLocation,
      jobType: mapJobType(jobData.job_employment_type),
      workType: mapWorkType(jobData.job_is_remote),
      isActive: true,
      openSlots: 1,
      ...(embeddingStr ? { embedding: sql`${embeddingStr}::vector` } : {}),
      expiresAt,
    })
    .returning({ id: schema.jobs.id });

  // Extract and link skills
  const skills = extractSkills(`${title} ${description} ${requirementsText}`);
  if (skills.length) await linkJobSkills(job.id, skills);

  return job.id;
}

// ── Public API ─────────────────────────────────────────────────────

export async function scrapeAndStoreJobs(
  query: string,
  location: string = "India",
  numPages: number = 1,
): Promise<{ fetched: number; stored: number; skipped: number; errors: number }> {
  if (!SYSTEM_RECRUITER_ID) {
    throw new Error("SYSTEM_RECRUITER_ID not set. Create a system user first.");
  }

  const jobs = await fetchFromJSearch(query, location, 1, numPages);

  let stored = 0;
  let skipped = 0;
  let errors = 0;

  for (const jobData of jobs) {
    try {
      const id = await storeJob(jobData);
      if (id) stored++;
      else skipped++;
    } catch (err) {
      console.error("Error storing job:", err);
      errors++;
    }
  }

  return { fetched: jobs.length, stored, skipped, errors };
}

export async function scrapeMultipleQueries(
  queries: string[],
  location: string = "India",
): Promise<{ totalFetched: number; totalStored: number; totalSkipped: number; totalErrors: number }> {
  let totalFetched = 0;
  let totalStored = 0;
  let totalSkipped = 0;
  let totalErrors = 0;

  for (const query of queries) {
    const result = await scrapeAndStoreJobs(query, location);
    totalFetched += result.fetched;
    totalStored += result.stored;
    totalSkipped += result.skipped;
    totalErrors += result.errors;
  }

  return { totalFetched, totalStored, totalSkipped, totalErrors };
}
